sudo: False

language: python
python:
  - "3.7"
cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.7


install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels diffpy
  - conda update conda
    # Install dependencies
  - conda create -n test --file requirements/run.txt python=3.7
  - source activate test
  - python setup.py install

script:
  - set -e
  - conda install --file requirements/test.txt
  - python -m pytest

notifications:
  email: false
